import { useEffect, useState } from "react"
import Head from "next/head"
import Link from "next/link"
import AppLayout from "../components/AppLayout"
import logo from "../public/logo-devter.svg"
import { colors } from "../styles/theme"
import Button from "../components/Button"
import GitHub from "../components/Icons/Github"
import loginWithGithub, {
  handleOnAuthStateChanged,
} from "../firebaseConfig/client"
import Avatar from "../components/Avatar"
import Image from "next/image"

export default function Home() {
  const [user, setUser] = useState(undefined)

  useEffect(() => {
    handleOnAuthStateChanged(setUser)
  }, [])

  const handleClick = () => {
    loginWithGithub()
      .then((res) => {
        setUser(res)
        console.log(user)
      })
      .catch((error) => console.error(error))
  }

  return (
    <div>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section>
          <Image src={logo} height="100%" width="120px" alt="logo devter" />
          <h1>Devter</h1>
          <h2>Talk about development with developers 👨‍💻 👩‍💻</h2>
          <br />
          {user === null && (
            <Button onClick={handleClick}>
              <GitHub />
              login with github
            </Button>
          )}
          {user && (
            <>
              <Avatar src={`${user.photo}`} username={user.username} />
            </>
          )}
        </section>
      </AppLayout>
      <style jsx>{`
        img {
          width: 120px;
        }
        div {
          margin-top: 16px;
        }
        section {
          display: grid;
          height: 100%;
          place-content: center;
          place-items: center;
        }
        h1 {
          color: ${colors.primary};
          font-weight: 800;
          font-size: 32px;
          margin-bottom: 16px;
        }
        h2 {
          color: ${colors.secondary};
          font-size: 21px;
          margin: 0;
        }
      `}</style>
    </div>
  )
}
